server:
  port: 9106

spring:
  cloud:
    stream:
      bindings:
        waiting_for_payment_input:
          destination: waitingForPayment
          group: default
          content-type: application/json
          consumer:
            max-attempts: 3
        payment_succeeded_output:
          destination: paymentSucceeded
          group: default
          content-type: application/json
          producer:
            required-groups: default
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/SCHEMA_PAYMENT?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1

security:
  oauth2:
    client:
      client-id: payment-service
      client-secret: secret
      access-token-uri: http://localhost:9999/uaa/oauth/token
      grant-type: client_credentials
    resource:
      token-info-uri: http://localhost:9999/uaa/oauth/check_token

flyway:
  enabled: true
  user: root
  password: root
  encoding: utf8
  validate-on-migrate: true