version: '2'

services:

  eureka-service:
    image: 192.168.1.88:5000/eureka-service
    container_name: eureka-service
    restart: always
    ports:
      - 8761:8761

  config-service:
    image: 192.168.1.88:5000/config-service
    container_name: config-service
    restart: always
    ports:
      - 8888:8888
    links:
      - eureka-service
      - rabbitmq
    environment:
      - EUREKA_HOST=eureka-service
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - eureka-service

  zuul-service:
    image: 192.168.1.88:5000/zuul-service
    ports:
      - 8000:8000
    environment:
      - EUREKA_HOST=192.168.1.88
    depends_on:
      - eureka-service
      - config-service
    restart: always

  oauth2-service:
    image: 192.168.1.88:5000/oauth2-service
    ports:
      - 9999:9999
    environment:
      - EUREKA_HOST=192.168.1.88
    depends_on:
      - eureka-service
      - config-service
    restart: always

  zipkin-service:
    image: 192.168.1.88:5000/zipkin-service
    ports:
      - 9411:9411
    environment:
      - RABBITMQ_HOST=192.168.1.88
      - EUREKA_HOST=192.168.1.88
    depends_on:
      - eureka-service
    restart: always

  hystrix-dashboard:
    image: 192.168.1.88:5000/hystrix-dashboard
    ports:
      - 8989:8989
      - 8990:8990
    restart: always