liquibase:
  change-log: classpath:db/changelog/changelog.xml
  default-schema: SCHEMA_PRODUCT
  drop-first: false
  enabled: true

---
spring:
  profiles: development

server:
  port: ${random.int[9040,9049]}

---
spring:
  profiles: test