liquibase:
  change-log: classpath:db/changelog/changelog.xml
  default-schema: SCHEMA_PAYMENT
  drop-first: false
  enabled: true

---
spring:
  profiles: development

server:
  port: ${random.int[9060,9069]}

---
spring:
  profiles: test