liquibase:
  change-log: classpath:db/changelog/changelog.xml
  default-schema: SCHEMA_PAYMENT
  drop-first: true
  enabled: false

---
spring:
  profiles: development

server:
  port: 9060

---
spring:
  profiles: test