version: '2'

services:

  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --character-set-client-handshake=0
    volumes:
      - /Users/Gavin/Developer/storage/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root

  rabbitmq:
    image: rabbitmq:3.6.5-management
    container_name: rabbitmq
    restart: always
    volumes:
      - /Users/Gavin/Developer/storage/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  kafka:
    image: spotify/kafka
    container_name: kafka
    restart: always
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - /Users/Gavin/Developer/storage/redis:/data
    ports:
      - 6379:6379

  logstash:
    image: logstash
    container_name: logstash
    restart: always
    command: logstash -e 'input { udp { port => 4560 codec => json } } output { elasticsearch { hosts => "elasticsearch:9200" } }'
    ports:
      - 4560:4560/udp
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    restart: always
    volumes:
      - /Users/Gavin/Developer/storage/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    links:
      - elasticsearch

#  zookeeper:
#    image: zookeeper
#    container_name: zookeeper
#    restart: always
#    ports:
#      - 2181:2181

#  registry:
#    image: registry
#    container_name: registry
#    volumes:
#      - /Users/Gavin/Developer/storage/registry:/var/lib/registry
#    ports:
#      - 5000:5000