liquibase:
  change-log: classpath:db/changelog/changelog.xml
  default-schema: SCHEMA_ORDER
  drop-first: true
  enabled: true

---
spring:
  profiles: development
  cloud:
    loadbalancer:
      retry:
        enabled: true

product-service:
  ribbon:
    ConnectTimeout: 250
    ReadTimeout: 1000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2

server:
  port: 9050

---
spring:
  profiles: test