
---
spring:
  profiles: development
  cloud:
    loadbalancer:
      retry:
        enabled: true

product-service:
  ribbon:
    ConnectTimeout: 250
    ReadTimeout: 1000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2

server:
  port: 9105

---
spring:
  profiles: test