spring:
  application:
    name: eureka-server

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#  instance:
#    lease-renewal-interval-in-seconds: 10

---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    hostname: peer1
#    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST2:localhost}:8762/eureka/

---
spring:
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    hostname: peer2
#    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST1:localhost}:8761/eureka/
