liquibase:
  change-log: classpath:db/changelog/changelog.xml
  default-schema: SCHEMA_USER
  drop-first: false
  enabled: true

---
spring:
  profiles: development

server:
  port: ${random.int[9010,9019]}

---
spring:
  profiles: test