spring:
  mail:
    host: smtp.yeah.net
    username: micro_service
    password: 1qaz2wsx
    properties:
      mail:
        smtp:
          auth: true
  cloud:
    stream:
      bindings:
        user_created_input:
          binder: rabbit
          destination: userCreated
          group: default
          content-type: application/json
          consumer:
            max-attempts: 3
      rabbit:
        bindings:
          user_created_input:
            consumer:
              acknowledgeMode: AUTO
              durableSubscription: true
              prefetch: 1
              requeueRejected: true
              autoBindDlq: true
              republishToDlq: true
              transacted: true

  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/SCHEMA_NOTIFICATION?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1

flyway:
  enabled: true
  user: root
  password: root
  encoding: utf8
  validate-on-migrate: true

mail:
  from: micro_service@yeah.net