liquibase:
  change-log: classpath:db/changelog/changelog.xml
  default-schema: SCHEMA_POINT
  drop-first: false
  enabled: true

---
spring:
  profiles: development

server:
  port: ${random.int[9020,9029]}

---
spring:
  profiles: test